WIDTH, HEIGHT = 500, 500
# Constants
PREDATOR_COST_PER_MOVE = -1
COORDINATION_BONUS = 10
NOT_COORDINATION_PENALTY = -20
TEAMWORK_BONUS = 10
PREY_REWARD_SURVIVAL = 10
PREY_REWARD_MOVE = 1
PREY_COST_CAPTURED = -11
PREDATOR_REWARD_CAPTURE = 11
CAPTURE_RADIUS = 150
MINIMUM_PREDATOR_DISTANCE = 100
MAXIMUM_PREDATOR_DISTANCE = 200