WIDTH, HEIGHT = 500, 500
# Constants
PREDATOR_COST_PER_MOVE = -1
COORDINATION_BONUS = 10
NOT_COORDINATION_PENALTY = -20
TEAMWORK_BONUS = 10
PREY_REWARD_SURVIVAL = 20
PREY_EVASION_REWARD = 10
PREY_INDIFFERENCE_COST = -20
PREY_REWARD_MOVE = 1
PREY_COST_CAPTURED = -10
PREY_COST_NEARLY_CAPTURED = -10
PREDATOR_REWARD_CAPTURE = 11
CAPTURE_RADIUS = 150
MINIMUM_PREDATOR_DISTANCE = 100
MAXIMUM_PREDATOR_DISTANCE = 200

# Learning Rates
ALPHA_DEER = 0.5
ALPHA_TIGER = 0.7
# Discount Factor
GAMMA = 0.618
